# Configure Netlify for SPA (Single Page Application) routing
[build]
  command = "npm install && npm run build"
  publish = "dist"
  base = "."

# Handle client-side routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
