# Configure Netlify for SPA (Single Page Application) routing
[build]
  command = "npm ci && npm run build"
  publish = "dist"
  base = "."

# Add environment variables to control build behavior
[build.environment]
  NODE_VERSION = "19.0.0"
  NPM_VERSION = "9.0.0"
  # Prevent warnings from being treated as errors in CI
  CI = "false"
  # Increase build memory limit
  NODE_OPTIONS = "--max_old_space_size=4096"

# Handle client-side routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
